#goal definition
string object_name
float32 max_time
---
#result definition
int16 end_state
geometry_msgs/PoseStamped object_pose
float32 end_confidence
---
#feedback
int16 state
float32 confidence
geometry_msgs/PoseStamped estimated_pose
